apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretreader
spec:
  replicas: 1
  selector:
    matchLabels:
      name: secretreader
  template:
    metadata:
      labels:
        name: secretreader
    spec:
      containers:
      - name: secretreader
        image: karthequian/secretreader:latest
        volumeMounts:
        - name: secret-volume
          mountPath: /tmp
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: apikey